version: '3'
services:
  mongo-express:
    image: mongo-express
    restart: on-failure
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=example
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mongo-express.rule=Host(`mongo-express.vagrantbox.local`)"
    depends_on:
      - mongo

